import type { JSX, PropsWithChildren } from "react";

export type GeoGebraProps = {
	algebraInputPosition?: string;
	allowStyleBar?: boolean;
	allowUpscale?: boolean;
	appletOnLoad?: () => void;
	appName?: string;
	autoHeight?: boolean;
	borderColor?: string;
	buttonBorderColor?: string;
	buttonRounding?: number;
	buttonShadows?: boolean;
	capturingThreshold?: number;
	country?: string;
	customToolBar?: string;
	debug?: boolean;
	editorBackgroundColor?: string;
	editorForegroundColor?: string;
	enable3d?: boolean;
	enableCAS?: boolean;
	enableFileFeatures?: boolean;
	enableLabelDrags?: boolean;
	enableRightClick?: boolean;
	enableShiftDragZoom?: boolean;
	errorDialogsActive?: boolean;
	filename?: string;
	ggbBase64?: string;
	height?: number;
	id?: string;
	keyboardType?: string;
	language?: string;
	LoadComponent?: (props: PropsWithChildren) => JSX.Element;
	material_id?: string;
	onReady?: () => void;
	perspective?: string;
	playButton?: boolean;
	preventFocus?: boolean;
	rounding?: string;
	scale?: number;
	scaleContainerClass?: string;
	showAlgebraInput?: boolean;
	showAnimationButton?: boolean;
	showFullscreenButton?: boolean;
	showLogging?: boolean;
	showMenuBar?: boolean;
	showResetIcon?: boolean;
	showStartTooltip?: boolean;
	showSuggestionButtons?: boolean;
	showToolBar?: boolean;
	showToolBarHelp?: boolean;
	showZoomButtons?: boolean;
	textmode?: boolean;
	useBrowserForJS?: boolean;
	width?: number;
};
